name: Interactive Mac Terminal
on: 
  workflow_dispatch:

jobs:
  interactive-session:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Interactive Terminal (Upterm)
        uses: lhotari/action-upterm@v1
        with:
          ## This will wait for you to connect before continuing
          wait-timeout-minutes: 60 
